from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np
import pygame

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agents_survival_reborn.constants import GENERATED_DIR, SPRITE_DIR
from agents_survival_reborn.data import SpriteSpec, sprite_specs
from sprite_chroma import clean_sprite_surface, remove_magenta_background


DEFAULT_COLUMNS = 12
DEFAULT_ROWS = 11
DEFAULT_CELL_SIZE = 128


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Slice a generated sprite atlas into the game's sprite PNG files.")
    parser.add_argument("atlas", type=Path, help="Path to the atlas PNG generated by ChatGPT.")
    parser.add_argument("--out", type=Path, default=SPRITE_DIR, help="Output directory for sliced sprites.")
    parser.add_argument("--columns", type=int, default=DEFAULT_COLUMNS)
    parser.add_argument("--rows", type=int, default=DEFAULT_ROWS)
    parser.add_argument("--cell-size", type=int, default=DEFAULT_CELL_SIZE)
    parser.add_argument("--chroma-key", default="ff00ff", help="Transparent background color for non-terrain cells, hex RGB.")
    parser.add_argument("--tolerance", type=int, default=34, help="RGB tolerance for removing chroma-key background.")
    parser.add_argument("--replace-existing", action="store_true", help="Overwrite existing sprite files.")
    parser.add_argument("--preview", action="store_true", help="Also save a normalized atlas preview in assets/generated.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    pygame.init()
    specs = sprite_specs()
    if len(specs) > args.columns * args.rows:
        raise SystemExit(f"Atlas grid has {args.columns * args.rows} cells, but the project needs {len(specs)} sprites.")

    atlas = _load_atlas(args.atlas, args.columns, args.rows, args.cell_size)
    key = _parse_hex_color(args.chroma_key)
    args.out.mkdir(parents=True, exist_ok=True)

    if args.preview:
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        pygame.image.save(atlas, str(GENERATED_DIR / "normalized_sprite_atlas.png"))

    written = 0
    skipped = 0
    for index, spec in enumerate(specs):
        target = args.out / spec.path
        if target.exists() and not args.replace_existing:
            skipped += 1
            continue
        cell = _slice_cell(atlas, index, args.columns, args.cell_size)
        sprite = _make_sprite(cell, spec, key, args.tolerance)
        pygame.image.save(sprite, str(target))
        written += 1

    pygame.quit()
    print(f"Sprites written: {written}")
    print(f"Sprites skipped: {skipped}")
    print(f"Output: {args.out}")
    return 0


def _load_atlas(path: Path, columns: int, rows: int, cell_size: int) -> pygame.Surface:
    if not path.exists():
        raise SystemExit(f"Atlas not found: {path}")
    atlas = pygame.image.load(str(path))
    target_size = (columns * cell_size, rows * cell_size)
    if atlas.get_size() != target_size:
        atlas = pygame.transform.smoothscale(atlas, target_size)
    return atlas.convert_alpha() if pygame.display.get_init() and pygame.display.get_surface() else atlas.copy()


def _slice_cell(atlas: pygame.Surface, index: int, columns: int, cell_size: int) -> pygame.Surface:
    col = index % columns
    row = index // columns
    rect = pygame.Rect(col * cell_size, row * cell_size, cell_size, cell_size)
    return atlas.subsurface(rect).copy()


def _make_sprite(cell: pygame.Surface, spec: SpriteSpec, key: tuple[int, int, int], tolerance: int) -> pygame.Surface:
    if spec.kind == "terrain":
        sprite = pygame.transform.smoothscale(cell, spec.size).convert_alpha() if pygame.display.get_surface() else pygame.transform.smoothscale(cell, spec.size)
        return clean_sprite_surface(sprite, preserve_opaque=True)[0]

    transparent = _remove_chroma_key(cell, key, tolerance)
    transparent = remove_magenta_background(transparent)[0]
    bbox = _alpha_bbox(transparent)
    if bbox is None:
        return pygame.Surface(spec.size, pygame.SRCALPHA)
    cropped = transparent.subsurface(bbox).copy()
    return clean_sprite_surface(_fit_centered(cropped, spec.size))[0]


def _remove_chroma_key(surface: pygame.Surface, key: tuple[int, int, int], tolerance: int) -> pygame.Surface:
    source = surface.convert_alpha() if pygame.display.get_surface() else surface.copy()
    rgb = pygame.surfarray.array3d(source)
    try:
        alpha = pygame.surfarray.array_alpha(source).copy()
    except ValueError:
        alpha = np.full(rgb.shape[:2], 255, dtype=np.uint8)
    key_array = np.array(key, dtype=np.int16)
    distance = np.abs(rgb.astype(np.int16) - key_array).max(axis=2)
    alpha[distance <= tolerance] = 0
    result = pygame.Surface(source.get_size(), pygame.SRCALPHA)
    pygame.surfarray.blit_array(result, rgb)
    pygame.surfarray.pixels_alpha(result)[:, :] = alpha
    return result


def _alpha_bbox(surface: pygame.Surface) -> pygame.Rect | None:
    alpha = pygame.surfarray.array_alpha(surface)
    ys, xs = np.where(alpha.T > 12)
    if len(xs) == 0 or len(ys) == 0:
        return None
    left = int(xs.min())
    right = int(xs.max()) + 1
    top = int(ys.min())
    bottom = int(ys.max()) + 1
    return pygame.Rect(left, top, right - left, bottom - top)


def _fit_centered(source: pygame.Surface, size: tuple[int, int]) -> pygame.Surface:
    width, height = source.get_size()
    target_w, target_h = size
    scale = min(target_w / max(1, width), target_h / max(1, height))
    new_size = (max(1, round(width * scale)), max(1, round(height * scale)))
    scaled = pygame.transform.smoothscale(source, new_size)
    result = pygame.Surface(size, pygame.SRCALPHA)
    result.blit(scaled, ((target_w - new_size[0]) // 2, (target_h - new_size[1]) // 2))
    return result


def _parse_hex_color(value: str) -> tuple[int, int, int]:
    clean = value.strip().lstrip("#")
    if len(clean) != 6:
        raise argparse.ArgumentTypeError("Expected RGB hex color, for example ff00ff.")
    try:
        return int(clean[0:2], 16), int(clean[2:4], 16), int(clean[4:6], 16)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("Expected RGB hex color, for example ff00ff.") from exc


if __name__ == "__main__":
    raise SystemExit(main())
